version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    image: kamel402/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db # anonymous volume with name

  redis:
    image: redis

volumes:
  mongo-db: