version: '3.8'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    command: npm run start:watch
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    volumes:
      - .:/usr/src/app # bind volume
      - /usr/src/app/node_modules # anonymous volume
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
